name: conditions

on:
  workflow_dispatch:

jobs:
  outputter:
    runs-on: ubuntu-latest
    outputs:
      val-one: ${{ steps.step.outputs.val-one }}
      val-two: ${{ steps.step.outputs.val-two }}
  
    steps:
      - id: step
        run: |
          echo "val-one=2.0" >> "$GITHUB_OUTPUT"
          echo "val-two=3.0" >> $GITHUB_OUTPUT
  
  print:
    runs-on: ubuntu-latest
    needs: outputter

    steps:
      - env:
          VALONE: ${{ needs.outputter.outputs.val-one }}
          VALTWO: ${{ needs.outputter.outputs.val-two }}
        run: echo "$VALONE, $VALTWO"

      - name: Conditional print less 10
        if: fromJSON(needs.outputter.outputs.val-one) < 10 && fromJSON(needs.outputter.outputs.val-two) < 10
        run: echo "Conditional print less 10"

      - name: Conditional print greater 0
        if: fromJSON(needs.outputter.output.val-two) > 0 && fromJSON(needs.outputter.outputs.val-two) > 0
        run: echo "Conditional print greater 0"
