name: Run dynmatrix

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  gen_matrix:
    name: Setup matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          MAT=$(cat << EOF
          {
            "include": [
              {
                "runner": "test-sknds-v1.3",
                "target": "skynode_s@v1.3"
              }
            ]
          }
          EOF
          )
          echo "matrix<<$EOF" >> $GITHUB_OUTPUT
          echo "$MAT" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
  
  sknd_hwt:
    name: Running ${{ matrix.target }}, on runner ${{ matrix.runner }}
    runs-on: ubuntu-latest
    needs: gen_matrix
    strategy:
      matrix: ${{ fromJson(needs.gen_matrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Start test
        run: make ${{ matrix.target }}
