name: Dynrunner

on:
  pull_request:
    branches:
      - '*'

jobs:
  select:
    name: Select dynamic runner
    runs-on: ubuntu-latest
    env:
      LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
    steps:
      - name: Output
        run: echo ${{ fromJSON(env.LABELS)[0] }}
