name: Dynrunner

on:
  pull_request:
    branches:
      - '*'

jobs:
  select:
    name: Select dynamic runner
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: echo ${{ fromJSON(github.event.pull_request.labels.*.name)[0] }}
