name: Fork

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  overwrite:
    name: Rev
    runs-on: ubuntu-latest
    steps:
      - name: Output Fork
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: echo "Fork"

      - name: Output Non-Fork
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: echo "Non-Fork"
  
