name: Rev

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  overwrite:
    name: Rev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Rev
        run: git rev-parse --verify HEAD
